# git-sumi ~ configuration file
# Config: https://sumi.rs/docs/configuration
# Rules: https://sumi.rs/docs/rules

# Processes each non-empty line as an individual commit.
split_lines = false

# Rule: Description must start with the specified case.
# Options: 'any', 'lower', 'upper'.
description_case = "upper"

# Rule: Use the imperative mood in the description.
# Example: 'Fix bug' instead of 'Fixed bug'.
imperative = true

# Rule: Header length limit.
# A value of 0 disables the rule.
max_header_length = 50

# Rule: Body line length limit.
# A value of 0 disables the rule.
max_body_length = 72
